### ISSUE TITLE
Doesn't actually work?

### ISSUE THREAD

**Issue by YSaxon** [cyal1/BcryptMontoya#2]
I love the idea of this extension, but it doesn't seem to be working at all. I thought at first it was something I did wrong in my own custom script, so I loaded and ran the examples/default.py script, and with the internal chromium browser navigated to https://wwww.example.com/api/test, and nothing gets changed. No notes, no HighlightColor, no BcryptMontoya header. Unfortunately I can't tell _why_ nothing is working. Perhaps you can suggest additional steps I can take to debug it?

**Comment by YSaxon** [comment]
Fwiw, I'm on a mac, and also having the same issue reported at https://github.com/Anof-cyber/PyCript/issues/8 for that extension. Maybe there's a general problem with calling into python from a mac environment?

**Comment by cyal1** [comment]
Hello, thank you for liking the extender. It works form me on mac M1, my version of burpsuite  is 2024.2.1.3, have you click the run button? and you should config the jython environment in Setting.

 <img width="927" alt="image" src="https://github.com/cyal1/BcryptMontoya/assets/33282478/441a98be-0f82-47a0-8594-fcece805887e">

Could you see any errors on the extended error tab?
<img width="641" alt="image" src="https://github.com/cyal1/BcryptMontoya/assets/33282478/71b151e4-330c-4dfd-8792-fd483306776f">

**Comment by YSaxon** [comment]
I downloaded your latest release jar, confirmed jython, exactly matched what you have, and still neither working nor giving any debug information...
Jython
<img width="1119" alt="Screenshot 2024-06-28 at 12 01 22 PM" src="https://github.com/cyal1/BcryptMontoya/assets/11711101/0ce3538f-c54c-411c-9124-38847f79e061">
Running your example code
<img width="1190" alt="Screenshot 2024-06-28 at 11 59 03 AM" src="https://github.com/cyal1/BcryptMontoya/assets/11711101/635736e9-db41-4c67-b2c3-dc3ad5c4933d">
Sent request from repeater as in your screenshot
<img width="1279" alt="Screenshot 2024-06-28 at 12 00 49 PM" src="https://github.com/cyal1/BcryptMontoya/assets/11711101/d14da8c9-48af-4151-8461-61da9787425c">
No Errors (or Output)    
<img width="959" alt="Screenshot 2024-06-28 at 11 59 31 AM" src="https://github.com/cyal1/BcryptMontoya/assets/11711101/87937cb0-a383-4393-879c-56cc68b091fd">


My Burp Suite version is 2024.5.4, which is _higher_ than your version. Might something have broken in the later versions? Could you try updating your Burp?
<img width="260" alt="Screenshot 2024-06-28 at 12 07 04 PM" src="https://github.com/cyal1/BcryptMontoya/assets/11711101/fcbedde9-f9e2-40d7-87da-9eb0058795d3">

**Comment by cyal1** [comment]
Hi, It's still working for me on 2024.5.4, how about the Detail tab on your Mac.
<img width="839" alt="image" src="https://github.com/cyal1/BcryptMontoya/assets/33282478/1125ce7b-42fb-4d22-8918-1208251381d9">

**Comment by cyal1** [comment]
The jar file I released was built on my M1 MacBook, which uses the ARM architecture. Perhaps for this reason, could you try building it on yourself device?

**Comment by cyal1** [comment]
Please download https://github.com/cyal1/BcryptMontoya/releases/tag/v0.1.8
